site_name: Lock-Unlock Documentatie
docs_dir: docs
site_dir: site
site_url: https://kadaster-labs.github.io/lock-unlock-docs/
repo_url: https://github.com/kadaster-labs/lock-unlock-docs
edit_uri: edit/main/docs/
nav:
  - Inleiding: index.md
  - Samenvatting: samenvatting.md
  - Federatieve bevraging: 
     - federatieve-bevraging/index.md
     - federatieve-bevraging/apis.md
     - federatieve-bevraging/linkeddata.md
     - federatieve-bevraging/testopstelling.md
     - federatieve-bevraging/informatiemodel.md
     - federatieve-bevraging/testdata.md
     - federatieve-bevraging/demonstrator.md
     - federatieve-bevraging/conclusies.md
  - Afscherming: 
    - afscherming/index.md
    - afscherming/deskresearch.md
    - afscherming/verantwoording.md
    - afscherming/requirements.md
    - afscherming/opties.md
    - afscherming/onderzoek.md
  - Autorisatie als Linked Data:
    - autorisatie-als-linkeddata/index.md
    - autorisatie-als-linkeddata/concept.md
    - autorisatie-als-linkeddata/authorization-ontology.md
    - autorisatie-als-linkeddata/implementaties.md
    - autorisatie-als-linkeddata/conclusies.md
    - autorisatie-als-linkeddata/vervolgonderzoek.md
  - conclusies/index.md
  - verdiepende-details/index.md
extra_css:
  - css/lock-unlock.css
theme:
  name: material
  palette:
    primary: custom
  language: nl
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant  
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    logo: material/lock
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
