site_name: Lock-Unlock Documentatie
docs_dir: docs
site_dir: site
site_url: https://kadaster-labs.github.io/lock-unlock-docs/
repo_url: https://github.com/kadaster-labs/lock-unlock-docs
edit_uri: edit/main/docs/
nav:
  - Samenvatting: index.md
  - Federatieve bevraging: 
     - federatieve-bevraging/index.md
     - API's: federatieve-bevraging/apis.md
     - Linked Data onderbouwing: federatieve-bevraging/linkeddata.md
     - Informatie model: federatieve-bevraging/informatiemodel.md
     - Testdata: federatieve-bevraging/testdata.md
     - Conclusies: federatieve-bevraging/conclusies.md
  - Afscherming: 
    - afscherming/index.md
    - Desk research: afscherming/deskresearch.md
    - Verantwoording: afscherming/verantwoording.md
    - Requirements: afscherming/requirements.md
    - Opties: afscherming/opties.md
    - Onderzoek: afscherming/onderzoek.md
  - Autorisatie als Linked Data:
    - autorisatie-als-linkeddata/index.md
    - Concept: autorisatie-als-linkeddata/concept.md
    - Authorization Onthology: autorisatie-als-linkeddata/authorization-onthology.md
    - Implementaties: autorisatie-als-linkeddata/implementaties.md
    - Conclusies: autorisatie-als-linkeddata/conclusies.md
    - Vervolgonderzoek: autorisatie-als-linkeddata/vervolgonderzoek.md
  - Algemene conclusies & aanbevelingen: 
    - conclusies/index.md
  - Verdiepende details: verdiepende-details/index.md
extra_css:
  - css/lock-unlock.css
theme:
  name: material
  palette:
    primary: custom
  language: nl
  features:
    - navigation.instant  
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    logo: material/antenna
    